spring:
  application:
    name: UserService
  datasource:
    #url: jdbc:mysql://localhost:3306/microservices # this will not create database automatically if not exists
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true # this will create database automatically if not exists
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

